---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-webapp-demo-calc-operator-v1-calculator
  failurePolicy: Fail
  name: mcalculator.kb.io
  rules:
  - apiGroups:
    - webapp.demo.calc-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calculators
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-webapp-demo-calc-operator-v1-calculator
  failurePolicy: Fail
  name: vcalculator.kb.io
  rules:
  - apiGroups:
    - webapp.demo.calc-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - calculators
  sideEffects: None
